controller_manager:
  ros__parameters:
    update_rate: 1000 #..or publish_rate?

    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - waist_thighL
      - thighL_shankL
    
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

    gains:
      waist_thighR:
        p: 1
        i: 0.001
        d: 0.065

      waist_thighL:
        p: 1
        i: 0.001
        d: 0.065

      thighR_shankR:
        p: 1
        i: 0.001
        d: 0.065

      thighL_shankL:
        p: 1
        i: 0.001
        d: 0.065

joint_position_controller:
  ros__parameters:
    joints:
      - boom_waist
      - outer_ring_inner_ring

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity

    gains:
      boom_waist:
        p: 1
        i: 0.001
        d: 0.065

      outer_ring_inner_ring:
        p: 1
        i: 0.001
        d: 0.065