controller_manager:
  ros__parameters:
    update_rate: 1000
    
    joint_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    
    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity
      - effort

    gains:
      joint1:
        p: 300.0
        i: 0.00
        d: 5.0

      joint2:
        p: 300.0
        i: 0.00
        d: 5.0

      joint3:
        p: 300.0
        i: 0.00
        d: 5.0

      joint4:
        p: 300.0
        i: 0.00
        d: 5.0
      
      joint5:
        p: 300.0
        i: 0.00
        d: 5.0
      
      joint6:
        p: 300.0
        i: 0.00
        d: 5.0
